/**
 * Tests for the AISI Lineage Toolkit endpoints.
 *
 *   - /api/aisi/companies — list of 9 labs with live inflation factors
 *   - /api/aisi/company/:id — drill into one lab's evidence base
 *   - /api/aisi/cross-company — hosts cited by 2+ companies
 *
 * These tests read from data/aisi/blocks/, which is generated by
 * data/aisi/scripts/snapshot.js from the sibling aisi-lineage-toolkit repo.
 * If the snapshot is missing, the first test asserts the API returns 503
 * with the correct error message.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { routeRequest } from "../server.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const AISI_DIR = join(ROOT, "data", "aisi", "blocks");

const KNOWN_COMPANIES = [
  "anthropic",
  "openai",
  "google-deepmind",
  "meta",
  "mistral",
  "xai",
  "deepseek",
  "alibaba-cloud",
  "z-ai",
];

function getRequest(pathname) {
  return routeRequest({
    method: "GET",
    pathname,
    search: new URLSearchParams(),
    body: {},
  });
}

// ---------------- /api/aisi/companies ----------------

test("aisi: /api/aisi/companies returns 9 labs sorted by inflation", async () => {
  if (!existsSync(AISI_DIR)) {
    const r = await getRequest("/api/aisi/companies");
    assert.equal(r.status, 503);
    const payload = JSON.parse(r.body);
    assert.match(payload.error, /snapshot not generated/i);
    return; // skip the rest — the snapshot hasn't been generated yet
  }
  const r = await getRequest("/api/aisi/companies");
  assert.equal(r.status, 200);
  const payload = JSON.parse(r.body);
  assert.equal(payload.ok, true);
  assert.equal(payload.companies.length, 9);
  for (const c of payload.companies) {
    assert.ok(KNOWN_COMPANIES.includes(c.id), `unexpected company: ${c.id}`);
    assert.equal(typeof c.title, "string");
    if (!c.error) {
      assert.ok(c.summary, `${c.id} should have a summary`);
      assert.equal(typeof c.summary.block_count, "number");
      assert.equal(typeof c.summary.document_count, "number");
      assert.equal(typeof c.summary.lineage_count, "number");
      assert.equal(typeof c.summary.inflation_factor, "number");
      assert.ok(c.summary.inflation_factor >= 0);
    }
  }
});

test("aisi: each company matches a known title", async () => {
  if (!existsSync(AISI_DIR)) return;
  const r = await getRequest("/api/aisi/companies");
  const payload = JSON.parse(r.body);
  const titles = payload.companies.map((c) => c.title).sort();
  assert.ok(titles.includes("Anthropic"));
  assert.ok(titles.includes("OpenAI"));
  assert.ok(titles.includes("Google DeepMind"));
  assert.ok(titles.includes("Meta"));
  assert.ok(titles.includes("Mistral"));
  assert.ok(titles.includes("xAI"));
  assert.ok(titles.includes("DeepSeek"));
  assert.ok(titles.includes("Alibaba Cloud"));
  assert.ok(titles.includes("Z.ai"));
});

// ---------------- /api/aisi/company/:id ----------------

test("aisi: /api/aisi/company/anthropic returns 20 excerpts → 3 lineages", async () => {
  if (!existsSync(AISI_DIR)) return;
  const r = await getRequest("/api/aisi/company/anthropic");
  if (r.status === 500) return; // registry may be missing
  assert.equal(r.status, 200);
  const payload = JSON.parse(r.body);
  assert.equal(payload.ok, true);
  assert.equal(payload.company, "anthropic");
  assert.equal(payload.title, "Anthropic");
  assert.equal(payload.summary.block_count, 20);
  // With the registry loaded, Anthropic's 20 blocks should collapse to 3 lineages
  if (payload.has_registry) {
    assert.equal(payload.summary.lineage_count, 3);
    assert.equal(payload.summary.inflation_factor, 6.667);
    assert.ok(payload.lineages && Object.keys(payload.lineages).length > 0);
  }
});

test("aisi: /api/aisi/company/unknown returns 404", async () => {
  if (!existsSync(AISI_DIR)) return;
  const r = await getRequest("/api/aisi/company/this-does-not-exist");
  assert.equal(r.status, 404);
  const payload = JSON.parse(r.body);
  assert.match(payload.error, /unknown company/i);
});

test("aisi: company endpoint surfaces correlated_documents", async () => {
  if (!existsSync(AISI_DIR)) return;
  const r = await getRequest("/api/aisi/company/anthropic");
  const payload = JSON.parse(r.body);
  if (!payload.ok) return;
  assert.ok(Array.isArray(payload.correlated_documents));
  // Anthropic has correlated documents (20 excerpts collapsing to 3)
  if (payload.has_registry) {
    assert.ok(payload.correlated_documents.length > 0);
    for (const cd of payload.correlated_documents) {
      assert.ok(cd.block_count >= 2, "correlated document should have 2+ blocks");
    }
  }
});

// ---------------- /api/aisi/cross-company ----------------

test("aisi: /api/aisi/cross-company returns shared hosts", async () => {
  if (!existsSync(AISI_DIR)) return;
  const r = await getRequest("/api/aisi/cross-company");
  assert.equal(r.status, 200);
  const payload = JSON.parse(r.body);
  assert.equal(payload.ok, true);
  assert.equal(payload.total_companies, 9);
  assert.ok(Array.isArray(payload.shared_roots));
  // Every entry must be cited by 2+ companies
  for (const root of payload.shared_roots) {
    assert.ok(root.company_count >= 2, `${root.host} must be in 2+ companies`);
    assert.ok(root.companies.length === root.company_count);
    assert.equal(typeof root.block_count, "number");
  }
});

test("aisi: /api/aisi/cross-company is sorted by company_count desc", async () => {
  if (!existsSync(AISI_DIR)) return;
  const r = await getRequest("/api/aisi/cross-company");
  const payload = JSON.parse(r.body);
  if (!payload.ok) return;
  for (let i = 1; i < payload.shared_roots.length; i++) {
    const prev = payload.shared_roots[i - 1];
    const cur = payload.shared_roots[i];
    assert.ok(
      prev.company_count > cur.company_count ||
        (prev.company_count === cur.company_count && prev.block_count >= cur.block_count),
      "shared_roots should be sorted by company_count desc, then block_count desc"
    );
  }
});

// ---------------- filesystem sanity ----------------

test("aisi: data/aisi/blocks/ contains one folder per company (when snapshot exists)", () => {
  if (!existsSync(AISI_DIR)) {
    // Skip silently — the snapshot is optional; CI may not have run it.
    return;
  }
  const dirs = readdirSync(AISI_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
  assert.ok(dirs.length > 0, "snapshot exists but contains no companies");
  for (const id of dirs) {
    assert.ok(
      existsSync(join(AISI_DIR, id, "evidence_blocks.json")),
      `${id}/evidence_blocks.json missing`
    );
  }
});
