#!/usr/bin/env node
/**
 * FLF Epistemic Stack — self-contained local server.
 *
 * Zero runtime dependencies. Uses node:http only. Binds to 127.0.0.1 (local-first,
 * never listens on a public address) on port 4318 (Core OS uses 4317; we sit beside it).
 *
 * Serves:
 *   - Static UI from web/ (landing, case view, about)
 *   - JSON API wrapping the epistemic engine
 *   - Endpoints reserved for local-LLM features (Phase 4): chat + alias proposer
 *
 * The router is exported (routeRequest) so the API can be tested without binding a port.
 */

import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname, normalize, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";

import { runCaseStudy } from "./src/epistemic/ingest.js";
import { getLlmStatus } from "./src/epistemic/llm.js";
import { proposeAliases, acceptAlias } from "./src/epistemic/alias_proposer.js";
import { chatWithCase } from "./src/epistemic/evidence_chat.js";
import { adjudicate, recordHumanPosition } from "./src/epistemic/adjudicate.js";
import { ADJUDICATION_JOBS } from "./src/epistemic/jobs.js";
import {
  summarizeModelShelf,
  pickChallenger,
  resolveModelLineage,
} from "./src/epistemic/model_identity.js";
import { resolveGenealogy } from "./src/epistemic/genealogy.js";
import { parseJsonEvidence } from "./parsers/json.js";
import { parseMarkdownEvidence } from "./parsers/markdown.js";
import { parsePdfEvidence } from "./parsers/pdf.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)));
const WEB_DIR = join(ROOT, "web");
const CASES_DIR = join(ROOT, "docs", "epistemic");
// AISI evidence snapshot lives under data/aisi/blocks/<company>/evidence_blocks.json.
// Generated by data/aisi/scripts/snapshot.js from the sibling aisi-lineage-toolkit repo.
const AISI_DIR = join(ROOT, "data", "aisi", "blocks");
// Human positions live beside the corpus, never inside it. Judging something and
// changing it stay separate acts.
const DECISIONS_DIR = join(ROOT, "decisions");
const PORT = Number(process.env.PORT) || 4318;
// In production (Render, Railway, Fly, etc.) bind to 0.0.0.0 so the host's
// reverse proxy can reach us. Local dev defaults to loopback only.
const HOST = process.env.HOST ?? (process.env.NODE_ENV === "production" ? "0.0.0.0" : "127.0.0.1");

const KNOWN_CASES = ["covid", "lhc", "eggs", "sample"];

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".md": "text/markdown; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

function json(status, payload) {
  return {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
    body: JSON.stringify(payload),
  };
}

async function readBody(req) {
  return new Promise((resolve) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
      if (raw.length > 1_000_000) req.destroy();
    });
    req.on("end", () => {
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch {
        resolve({ _raw: raw });
      }
    });
    req.on("error", () => resolve({}));
  });
}

/**
 * Pure-ish router. Exported for tests.
 * @param {{ method: string, pathname: string, search: URLSearchParams, body?: object }} req
 */
export async function routeRequest({ method, pathname, search, body = {} }) {
  // ---- Static UI ---------------------------------------------------------
  if (method === "GET" && (pathname === "/" || pathname === "")) {
    try {
      const html = await readFile(join(WEB_DIR, "index.html"), "utf8");
      return { status: 200, headers: { "content-type": "text/html; charset=utf-8" }, body: html };
    } catch (e) {
      return { status: 500, headers: { "content-type": "text/plain" }, body: `index.html missing: ${e.message}` };
    }
  }


  if (method === "GET" && pathname === "/case.html") {
    try {
      const html = await readFile(join(WEB_DIR, "case.html"), "utf8");
      return { status: 200, headers: { "content-type": "text/html; charset=utf-8" }, body: html };
    } catch {
      return { status: 404, headers: { "content-type": "text/plain" }, body: "case.html missing" };
    }
  }

  if (method === "GET" && pathname.startsWith("/static/")) {
    // /static/foo.css → web/static/foo.css  (web/ is the UI root; static/ is a subdir of it)
    const rel = pathname.slice("/static/".length);
    const candidate = join(WEB_DIR, "static", rel);
    const safe = normalize(candidate);
    if (!safe.startsWith(join(WEB_DIR, "static"))) return json(400, { error: "bad path" });
    if (!existsSync(safe)) return json(404, { error: "not found" });
    const data = await readFile(safe);
    return {
      status: 200,
      headers: { "content-type": MIME[extname(safe).toLowerCase()] ?? "application/octet-stream" },
      body: data,
    };
  }

  // ---- JSON API ----------------------------------------------------------

  if (method === "GET" && pathname === "/api/ping") {
    return json(200, { ok: true, ts: Date.now(), service: "flf-epistack" });
  }

  // ---- User-supplied analysis (drag-drop / paste / API) -------------------
  // Accepts JSON, Markdown, or PDF. Dispatches to the appropriate parser,
  // runs the genealogy engine, returns the three-level summary.
  //
  // Inputs:
  //   POST /api/analyze
  //     Content-Type: application/json  → body = { text, format?: "json"|"md" }
  //     Content-Type: text/markdown      → body = markdown text
  //     Content-Type: application/pdf    → body = raw PDF bytes
  //     Content-Type: multipart/form-data → file field "file"
  if (method === "POST" && pathname === "/api/analyze") {
    // The router is pure — content-type is not in scope. PDF and multipart
    // are handled in handle() before this router is invoked; this branch
    // covers JSON and Markdown bodies (parsed text in body.text / body._raw).
    // Anything else gets a 400.
    let text = body?.text ?? "";
    let format = body?.format ?? "auto";
    if (!text && typeof body?._raw === "string") text = body._raw;
    if (!text) {
      return json(400, {
        error: "empty body. POST JSON { text, format? }, markdown raw, or PDF/multipart directly.",
      });
    }

    // If a markdown content-type was sent raw, routeRequest's readBody will
    // have stored it in _raw. We auto-detect format.
    if (format === "auto") {
      const trimmed = text.trim();
      if (trimmed.startsWith("{") || trimmed.startsWith("[")) format = "json";
      else format = "md";
    }

    let parsed;
    if (format === "json") {
      parsed = parseJsonEvidence(text);
    } else if (format === "md" || format === "markdown") {
      parsed = parseMarkdownEvidence(text);
    } else {
      return json(400, { error: `unsupported format: ${format}` });
    }

    if (!parsed.ok) {
      return json(400, { ok: false, error: parsed.error, hint: parsed.hint ?? null });
    }

    try {
      const genealogy = resolveGenealogy(parsed.blocks, { aliases: {}, registry: {} });
      const summary = summarise(genealogy, parsed.blocks.length);
      return json(200, {
        ok: true,
        source: format,
        block_count: parsed.blocks.length,
        summary,
        assessment_line: summary.assessment_line,
      });
    } catch (e) {
      return json(500, { ok: false, error: e.message });
    }
  }

  if (method === "GET" && pathname === "/api/cases") {
    const cases = [];
    for (const id of KNOWN_CASES) {
      const dir = join(CASES_DIR, id);
      if (!existsSync(dir)) continue;
      try {
        const result = runCaseStudy(dir);
        cases.push({
          id,
          title: caseTitle(id),
          summary: result.summary,
          subquestion: readSubquestion(dir),
        });
      } catch (e) {
        cases.push({ id, title: caseTitle(id), error: e.message });
      }
    }
    return json(200, { ok: true, cases });
  }

  const caseMatch = pathname.match(/^\/api\/case\/([a-z0-9_-]+)$/);
  if (method === "GET" && caseMatch) {
    const id = caseMatch[1];
    if (!KNOWN_CASES.includes(id)) return json(404, { error: `unknown case: ${id}` });
    const dir = join(CASES_DIR, id);
    if (!existsSync(dir)) return json(404, { error: `case folder missing: ${id}` });
    try {
      const result = runCaseStudy(dir);
      const subquestion = readSubquestion(dir);
      return json(200, { ok: true, case: id, subquestion, ...result });
    } catch (e) {
      return json(500, { ok: false, error: e.message });
    }
  }

  if (method === "GET" && pathname === "/api/llm/status") {
    const status = await getLlmStatus();
    return json(200, { ok: true, ...status });
  }

  if (method === "GET" && pathname === "/api/aisi/companies") {
    if (!existsSync(AISI_DIR)) return json(503, { ok: false, error: "AISI snapshot not generated. Run: node data/aisi/scripts/snapshot.js" });
    const dirs = readdirSync(AISI_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
    const companies = [];
    for (const id of dirs) {
      const result = loadAisiCompany(id);
      if (result.error) {
        companies.push({ id, title: aisiTitle(id), error: result.error });
      } else {
        companies.push({
          id,
          title: aisiTitle(id),
          block_count: result.block_count,
          has_registry: result.has_registry,
          summary: result.summary,
        });
      }
    }
    return json(200, { ok: true, companies });
  }

  const aisiMatch = pathname.match(/^\/api\/aisi\/company\/([a-z0-9_-]+)$/);
  if (method === "GET" && aisiMatch) {
    const id = aisiMatch[1];
    const result = loadAisiCompany(id);
    if (result.error === "not found") return json(404, { error: `unknown company: ${id}` });
    if (result.error) return json(500, { ok: false, error: result.error });
    return json(200, {
      ok: true,
      company: id,
      title: aisiTitle(id),
      block_count: result.block_count,
      has_registry: result.has_registry,
      summary: result.summary,
      assessment_line: result.summary.assessment_line,
      correlated_documents: result.correlated_documents,
      // Echo lineage group names so the UI can show what the lineages are
      lineages: result.lineages,
    });
  }

  // Cross-company findings: which roots recur across multiple AISI companies.
  // Returns hosts that appear in 2+ companies' evidence bases — the hidden
  // correlations the AISI report calls out (SWE-bench, MMLU, HumanEval, etc.).
  if (method === "GET" && pathname === "/api/aisi/cross-company") {
    if (!existsSync(AISI_DIR)) return json(503, { ok: false, error: "AISI snapshot not generated. Run: node data/aisi/scripts/snapshot.js" });
    const dirs = readdirSync(AISI_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
    const hostMap = new Map(); // host -> { companies:Set, count }
    for (const id of dirs) {
      const file = join(AISI_DIR, id, "evidence_blocks.json");
      if (!existsSync(file)) continue;
      try {
        const raw = JSON.parse(readFileSync(file, "utf8"));
        const blocks = Array.isArray(raw) ? raw : (raw.blocks ?? []);
        for (const b of blocks) {
          const url = b?.provenance?.context;
          if (typeof url !== "string") continue;
          try {
            const u = new URL(url);
            const host = u.hostname.replace(/^www\./, "");
            if (!hostMap.has(host)) hostMap.set(host, { host, companies: new Set(), block_count: 0 });
            const entry = hostMap.get(host);
            entry.companies.add(id);
            entry.block_count += 1;
          } catch {
            /* skip invalid URLs */
          }
        }
      } catch {
        /* skip broken files */
      }
    }
    const shared = [...hostMap.values()]
      .filter((h) => h.companies.size >= 2)
      .map((h) => ({ host: h.host, companies: [...h.companies].sort(), block_count: h.block_count, company_count: h.companies.size }))
      .sort((a, b) => b.company_count - a.company_count || b.block_count - a.block_count);
    return json(200, { ok: true, shared_roots: shared, total_companies: dirs.length });
  }

  // The tool's own three-level counting, pointed at the model shelf on this
  // machine. Reports how much adjudication independence is actually available
  // here rather than how much we would like to claim.
  if (method === "GET" && pathname === "/api/llm/independence") {
    const status = await getLlmStatus();
    const installed = status?.models ?? [];
    const shelf = summarizeModelShelf(installed);
    const proposer = status?.model ?? installed[0] ?? null;
    const challenger = proposer ? pickChallenger(proposer, installed) : null;
    return json(200, {
      ok: true,
      ollama_reachable: Boolean(status?.ok),
      ...shelf,
      proposer,
      proposer_lineage: proposer ? resolveModelLineage(proposer).lineage_id : null,
      challenger,
      // Mechanical always runs, so a machine with no models still gets one
      // genuinely independent challenger — hence 'weak' rather than 'none'.
      available_grade: challenger ? "moderate" : "weak",
      unresolvable:
        "Level 4 — shared pretraining corpora across open models — is real and not " +
        "resolvable, because no major open model discloses its training data.",
    });
  }

  // ---- Phase 4: LLM endpoints (require Ollama) ---------------------------

  if (method === "POST" && pathname === "/api/aliases/propose") {
    const caseId = body?.case ?? search?.get("case");
    if (!caseId || !KNOWN_CASES.includes(caseId)) {
      return json(400, { error: "case required (one of: " + KNOWN_CASES.join(", ") + ")" });
    }
    const dir = join(CASES_DIR, caseId);
    try {
      const result = await proposeAliases(dir, body?.options ?? {});
      return json(200, { ok: true, case: caseId, proposals: result.proposals, model: result.model });
    } catch (e) {
      return json(503, { ok: false, error: e.message });
    }
  }

  if (method === "POST" && pathname === "/api/aliases/accept") {
    const caseId = body?.case;
    const proposal = body?.proposal;
    if (!caseId || !proposal) return json(400, { error: "case + proposal required" });
    if (!KNOWN_CASES.includes(caseId)) return json(404, { error: `unknown case: ${caseId}` });
    const dir = join(CASES_DIR, caseId);
    try {
      const result = acceptAlias(dir, proposal);
      return json(200, { ok: true, ...result });
    } catch (e) {
      return json(500, { ok: false, error: e.message });
    }
  }

  if (method === "POST" && pathname === "/api/adjudicate") {
    const caseId = body?.case;
    const job = String(body?.job ?? "").trim();
    if (!caseId || !KNOWN_CASES.includes(caseId)) {
      return json(400, { error: "case required (one of: " + KNOWN_CASES.join(", ") + ")" });
    }
    if (!ADJUDICATION_JOBS[job]) {
      return json(400, { error: "job required (one of: " + Object.keys(ADJUDICATION_JOBS).join(", ") + ")" });
    }
    const dir = join(CASES_DIR, caseId);
    try {
      const { blocks, claim_graph, measurement_roots } = runCaseStudy(dir);
      const spec = ADJUDICATION_JOBS[job];
      const record = await adjudicate({
        question: body?.question || spec.question,
        jobType: job,
        blocks,
        instructions: spec.instructions,
        // Mechanical check C4 needs the graph to spot counter-evidence the
        // reasoning walked past.
        edges: claim_graph?.edges ?? [],
        cwd: dir,
        // Declared in the case's source_registry.json, never in a request body:
        // an HTTP caller must not get to choose where a command runs.
        measurementRoots: measurement_roots ?? {},
        opts: body?.options ?? {},
      });
      return json(200, { ok: true, case: caseId, record });
    } catch (e) {
      return json(503, { ok: false, error: e.message });
    }
  }

  // Stage 4. The human is the only lineage on the panel that is not another
  // instance of the thing being checked, so recording their position is what
  // lifts independence to `strong`. It is never required — accept works without
  // it, at a lower grade, and the UI says so.
  if (method === "POST" && pathname === "/api/decision") {
    const caseId = body?.case;
    const job = String(body?.job ?? "").trim();
    const record = body?.record;
    const position = body?.position ?? {};
    if (!caseId || !KNOWN_CASES.includes(caseId)) {
      return json(400, { error: "case required (one of: " + KNOWN_CASES.join(", ") + ")" });
    }
    if (!ADJUDICATION_JOBS[job]) {
      return json(400, { error: "job required (one of: " + Object.keys(ADJUDICATION_JOBS).join(", ") + ")" });
    }
    if (!record || typeof record !== "object") {
      return json(400, { error: "record required" });
    }
    if (!["accepted", "rejected"].includes(position.decision)) {
      return json(400, { error: "position.decision must be 'accepted' or 'rejected'" });
    }

    try {
      const updated = recordHumanPosition(record, {
        ...position,
        answered_at: new Date().toISOString(),
      });

      // caseId and job are both validated against fixed allow-lists above, so
      // the filename cannot be steered outside this directory.
      if (!existsSync(DECISIONS_DIR)) mkdirSync(DECISIONS_DIR, { recursive: true });
      const file = join(DECISIONS_DIR, `${caseId}-${job}-${Date.now()}.json`);
      writeFileSync(
        file,
        JSON.stringify(
          {
            case: caseId,
            job,
            decision: updated.human_decision,
            verdict: updated.verdict,
            independence_grade: updated.challenge_panel?.independence_grade ?? null,
            conclusion: updated.conclusion ?? null,
            model: updated.model ?? null,
            human_position: updated.human_position,
            human_engaged: updated.human_engaged,
            recorded_at: new Date().toISOString(),
          },
          null,
          2
        ) + "\n",
        "utf8"
      );

      return json(200, {
        ok: true,
        record: updated,
        // Relative, so the UI can name the file without leaking a home directory.
        saved_to: `decisions/${basename(file)}`,
      });
    } catch (e) {
      return json(500, { ok: false, error: e.message });
    }
  }

  if (method === "POST" && pathname === "/api/chat") {
    const caseId = body?.case;
    const question = String(body?.question ?? "").trim();
    const history = Array.isArray(body?.history) ? body.history : [];
    if (!caseId || !KNOWN_CASES.includes(caseId)) {
      return json(400, { error: "case required (one of: " + KNOWN_CASES.join(", ") + ")" });
    }
    if (!question) return json(400, { error: "question required" });
    const dir = join(CASES_DIR, caseId);
    try {
      const result = await chatWithCase(dir, question, history, body?.options ?? {});
      return json(200, { ok: true, case: caseId, ...result });
    } catch (e) {
      return json(503, { ok: false, error: e.message });
    }
  }

  return json(404, { error: `not found: ${method} ${pathname}` });
}

/**
 * Build the user-facing summary from a resolveGenealogy() result. Mirrors
 * the shape of runCaseStudy().summary so the UI is consistent across the
 * built-in cases and user uploads.
 */
function summarise(genealogy, blockCount) {
  const document_clusters = genealogy.documentClusters ?? [];
  const lineage_clusters = genealogy.lineageClusters ?? [];
  const document_count = document_clusters.length;
  const lineage_count = lineage_clusters.length;
  const inflation_factor =
    blockCount > 0 ? Number((blockCount / Math.max(lineage_count, 1)).toFixed(3)) : 0;
  const correlated_document_count = document_clusters.filter((c) => c.block_count > 1).length;

  return {
    block_count: blockCount,
    claim_count: blockCount,
    document_count,
    lineage_count,
    independent_root_count: lineage_count,
    correlated_document_count,
    correlated_lineage_count: 0,
    inflation_factor,
    assessment_line:
      `${blockCount} excerpt${blockCount === 1 ? "" : "s"} cited, drawn from ` +
      `${document_count} document${document_count === 1 ? "" : "s"}, tracing to ` +
      `${lineage_count} independent lineage${lineage_count === 1 ? "" : "s"}. ` +
      `Treat as ${lineage_count} independent source${lineage_count === 1 ? "" : "s"}, not ${blockCount}.`,
  };
}

function caseTitle(id) {
  return {
    covid: "COVID-19 origins",
    lhc: "Could the LHC create a dangerous black hole?",
    eggs: "Are eggs bad for you?",
    sample: "Worked example (editable)",
  }[id] ?? id;
}

const AISI_TITLES = {
  "anthropic": "Anthropic",
  "openai": "OpenAI",
  "google-deepmind": "Google DeepMind",
  "meta": "Meta",
  "mistral": "Mistral",
  "xai": "xAI",
  "deepseek": "DeepSeek",
  "alibaba-cloud": "Alibaba Cloud",
  "z-ai": "Z.ai",
};
function aisiTitle(id) {
  return AISI_TITLES[id] ?? id;
}

/**
 * Load + run the Epistack engine on one AISI company's evidence blocks.
 * Mirrors scripts/aisi-run.js from the sibling aisi-lineage-toolkit repo:
 * reads the source registry, hydrates provenance.context as a URL string,
 * and indexes the registry by every key the engine might look up.
 *
 * @returns { id, block_count, has_registry, summary, correlated_documents, lineages }
 *          or { error } for not-found / read failures.
 */
function loadAisiCompany(id) {
  const dir = join(AISI_DIR, id);
  if (!existsSync(dir)) return { error: "not found" };
  const blocksFile = join(dir, "evidence_blocks.json");
  const registryFile = join(dir, "source_registry.json");
  if (!existsSync(blocksFile)) return { error: "not found" };
  try {
    const blocksRaw = JSON.parse(readFileSync(blocksFile, "utf8"));
    const blocksArray = Array.isArray(blocksRaw) ? blocksRaw : (blocksRaw.blocks ?? []);

    let registryForEngine = {};
    let lineages = {};
    const hasRegistry = existsSync(registryFile);
    if (hasRegistry) {
      const registry = JSON.parse(readFileSync(registryFile, "utf8"));
      lineages = registry.lineages ?? {};
      for (const [docId, entry] of Object.entries(registry.documents ?? {})) {
        if (!entry || typeof entry !== "object") continue;
        registryForEngine[docId] = entry;
        if (entry.url) registryForEngine[entry.url] = entry;
        if (entry.document_id) {
          registryForEngine[entry.document_id] = entry;
          const baseId = entry.document_id.split(/[-_]/).slice(0, 2).join("-");
          if (baseId !== entry.document_id) registryForEngine[baseId] = entry;
        }
      }
    }

    // Hydrate: ensure every block has provenance.context as a URL string,
    // falling back through source.url → source.identifier → registry lookup.
    const hydratedBlocks = blocksArray.map((block) => {
      const copy = JSON.parse(JSON.stringify(block));
      if (!copy.provenance) copy.provenance = {};
      let url = copy.source?.url;
      if (!url && copy.source?.identifier && registryForEngine[copy.source.identifier]?.url) {
        url = registryForEngine[copy.source.identifier].url;
      }
      const ctx = copy.provenance.context;
      if (typeof ctx === "string") {
        if (url && !ctx.includes(url)) copy.provenance.context = url;
      } else if (ctx && typeof ctx === "object" && ctx.url) {
        copy.provenance.context = ctx.url;
      } else if (url) {
        copy.provenance.context = url;
      }
      return copy;
    });

    const genealogy = resolveGenealogy(hydratedBlocks, { registry: registryForEngine });
    const summary = summarise(genealogy, blocksArray.length);
    const correlated_documents = (genealogy.documentClusters ?? []).filter((c) => c.block_count > 1);
    return {
      id,
      block_count: blocksArray.length,
      has_registry: hasRegistry,
      summary,
      correlated_documents,
      lineages,
    };
  } catch (e) {
    return { error: e.message };
  }
}

function readSubquestion(caseDir) {
  try {
    const p = join(caseDir, "SUBQUESTION.md");
    if (!existsSync(p)) return null;
    return readFileSync(p, "utf8").trim();
  } catch {
    return null;
  }
}

/**
 * Read the request body as a raw Buffer (for PDF upload).
 * Caps at 25 MB to keep memory bounded on the Render free tier.
 */
function readRawBody(req, maxBytes = 25 * 1024 * 1024) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    req.on("data", (chunk) => {
      total += chunk.length;
      if (total > maxBytes) {
        req.destroy();
        reject(new Error(`request body exceeds ${maxBytes} bytes`));
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks, total)));
    req.on("error", reject);
  });
}

/**
 * Parse a multipart/form-data body and return the first file part.
 * Tiny purpose-built parser — no dependencies. Looks for a part with a
 * filename; returns { filename, contentType, bytes } or null.
 */
function parseMultipartForFile(buffer, boundary) {
  const sep = Buffer.from(`--${boundary}`);
  const parts = [];
  let start = 0;
  while (start < buffer.length) {
    const idx = buffer.indexOf(sep, start);
    if (idx === -1) break;
    const next = buffer.indexOf(sep, idx + sep.length);
    const slice = next === -1 ? buffer.slice(idx + sep.length) : buffer.slice(idx + sep.length, next);
    parts.push(slice);
    if (next === -1) break;
    start = next;
  }
  for (const part of parts) {
    const headerEnd = part.indexOf("\r\n\r\n");
    if (headerEnd === -1) continue;
    const headerText = part.slice(0, headerEnd).toString("utf8");
    if (!/filename=/i.test(headerText)) continue;
    const filenameMatch = headerText.match(/filename="?([^";\r\n]+)"?/i);
    const ctMatch = headerText.match(/content-type:\s*([^\r\n]+)/i);
    // Strip the trailing \r\n before the next boundary.
    let body = part.slice(headerEnd + 4);
    if (body.length >= 2 && body[body.length - 2] === 0x0d && body[body.length - 1] === 0x0a) {
      body = body.slice(0, -2);
    }
    return {
      filename: filenameMatch?.[1] ?? "uploaded.bin",
      contentType: ctMatch?.[1]?.trim() ?? "application/octet-stream",
      bytes: body,
    };
  }
  return null;
}

async function handle(req, res) {
  try {
    const url = new URL(req.url, `http://${HOST}`);
    const ctype = String(req.headers["content-type"] ?? "").toLowerCase();

    // ----- PDF or multipart: handle here, never as parsed JSON. -----
    if (req.method === "POST" && url.pathname === "/api/analyze") {
      if (ctype.startsWith("multipart/form-data")) {
        const m = ctype.match(/boundary=(?:"([^"]+)"|([^;]+))/i);
        const boundary = m?.[1] ?? m?.[2];
        if (!boundary) {
          res.writeHead(400, { "content-type": "application/json" });
          res.end(JSON.stringify({ ok: false, error: "multipart boundary missing" }));
          return;
        }
        const raw = await readRawBody(req);
        const file = parseMultipartForFile(raw, boundary);
        if (!file) {
          res.writeHead(400, { "content-type": "application/json" });
          res.end(JSON.stringify({ ok: false, error: "no file part in multipart body" }));
          return;
        }
        await handleAnalyze(res, file.bytes, file.filename, file.contentType);
        return;
      }
      if (ctype === "application/pdf") {
        const bytes = await readRawBody(req);
        await handleAnalyze(res, bytes, "uploaded.pdf", "application/pdf");
        return;
      }
      // else fall through to JSON parsing.
    }

    const body = ["POST", "PUT", "PATCH"].includes(req.method) ? await readBody(req) : {};
    const result = await routeRequest({
      method: req.method,
      pathname: url.pathname,
      search: url.searchParams,
      body,
    });
    res.writeHead(result.status, result.headers);
    res.end(result.body);
  } catch (e) {
    res.writeHead(500, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: false, error: e.message }));
  }
}

async function handleAnalyze(res, bytes, filename, contentType) {
  let parsed;
  if (contentType === "application/pdf" || filename.toLowerCase().endsWith(".pdf")) {
    parsed = await parsePdfEvidence(bytes, filename);
  } else if (contentType.startsWith("text/markdown") || filename.toLowerCase().endsWith(".md")) {
    parsed = parseMarkdownEvidence(bytes.toString("utf8"));
  } else if (contentType.startsWith("application/json") || filename.toLowerCase().endsWith(".json")) {
    parsed = parseJsonEvidence(bytes.toString("utf8"));
  } else {
    // Fall back: try JSON first, then markdown.
    const text = bytes.toString("utf8");
    const trimmed = text.trim();
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
      parsed = parseJsonEvidence(text);
    } else {
      parsed = parseMarkdownEvidence(text);
    }
  }
  if (!parsed.ok) {
    res.writeHead(400, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: false, error: parsed.error, hint: parsed.hint ?? null }));
    return;
  }
  try {
    const genealogy = resolveGenealogy(parsed.blocks, { aliases: {}, registry: {} });
    const summary = summarise(genealogy, parsed.blocks.length);
    const source = contentType === "application/pdf" || filename.toLowerCase().endsWith(".pdf")
      ? "pdf"
      : filename.toLowerCase().endsWith(".md") || contentType.startsWith("text/markdown")
      ? "md"
      : "json";
    res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
    res.end(
      JSON.stringify({
        ok: true,
        source,
        filename,
        block_count: parsed.blocks.length,
        summary,
        assessment_line: summary.assessment_line,
        text_excerpt: parsed.text_excerpt ?? null,
      })
    );
  } catch (e) {
    res.writeHead(500, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: false, error: e.message }));
  }
}

// ---- Boot (when run directly, not when imported for tests) --------------
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const server = createServer(handle);
  server.listen(PORT, HOST, () => {
    console.log(`FLF Epistemic Stack — local server`);
    console.log(`  http://${HOST}:${PORT}`);
    console.log(`  cases: ${KNOWN_CASES.join(", ")}`);
    console.log(`  Press Ctrl+C to stop.`);
  });
}
