#!/usr/bin/env node
/**
 * Run every assessment job against every case and record the results.
 *
 * Turns "these jobs run" into "here is what they produced, and here is how
 * often their citations held up". Writes a reviewable report plus the raw
 * records, so the claim that a desideratum is met can be checked rather than
 * taken on faith.
 *
 * Usage: node scripts/validate-jobs.js [case ...]
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { runCaseStudy } from "../src/epistemic/ingest.js";
import { adjudicate } from "../src/epistemic/adjudicate.js";
import { ADJUDICATION_JOBS, JOB_NAMES } from "../src/epistemic/jobs.js";
import { getLlmStatus } from "../src/epistemic/llm.js";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const argv = process.argv.slice(2);

// Regenerating the write-up should not cost another 15 model calls, so the
// records are the durable artifact and the report is derived from them.
const fromRecords = argv.includes("--from-records");
const cases = argv.filter((a) => !a.startsWith("--"));
const caseList = cases.length ? cases : ["covid", "lhc", "eggs"];

const outDir = join(repoRoot, "docs", "validation");
mkdirSync(outDir, { recursive: true });
const recordsPath = join(outDir, "records.json");

let results;
let modelName;

if (fromRecords) {
  if (!existsSync(recordsPath)) {
    console.error(`No records at ${recordsPath}. Run without --from-records first.`);
    process.exit(1);
  }
  results = JSON.parse(readFileSync(recordsPath, "utf8"));
  modelName = results.find((r) => r.record?.model)?.record.model ?? "unknown";
  console.log(`Rebuilding report from ${results.length} saved records (${modelName})`);
} else {
  const status = await getLlmStatus();
  if (!status.ready) {
    console.error(`LLM not ready: ${status.reason}`);
    process.exit(1);
  }
  modelName = status.model;

  console.log(`Validating ${JOB_NAMES.length} jobs x ${caseList.length} cases = ${JOB_NAMES.length * caseList.length} runs`);
  console.log(`Model: ${modelName}\n`);

  results = [];
  let n = 0;
  const total = JOB_NAMES.length * caseList.length;

  for (const caseName of caseList) {
    const caseDir = join(repoRoot, "docs", "epistemic", caseName);
    const { blocks } = runCaseStudy(caseDir);

    for (const job of JOB_NAMES) {
      n++;
      const started = Date.now();
      process.stdout.write(`[${n}/${total}] ${caseName}/${job} ... `);
      try {
        const record = await adjudicate({
          question: ADJUDICATION_JOBS[job].question,
          jobType: job,
          blocks,
          instructions: ADJUDICATION_JOBS[job].instructions,
        });
        const secs = ((Date.now() - started) / 1000).toFixed(0);
        const v = record.verification;
        const weak = v?.weak_steps ? `, ${v.weak_steps} weak` : "";
        console.log(
          `${record.verdict} (${v ? `${v.verified_steps}/${v.total_steps} steps${weak}` : "n/a"}, ${secs}s)`
        );
        results.push({ case: caseName, job, record });
      } catch (e) {
        console.log(`ERROR ${e.message}`);
        results.push({ case: caseName, job, error: e.message });
      }
    }
  }

  // Merge over any previous run so reruns of a single case do not discard the rest.
  if (existsSync(recordsPath)) {
    const prior = JSON.parse(readFileSync(recordsPath, "utf8"));
    const fresh = new Set(results.map((r) => `${r.case}/${r.job}`));
    results = [...prior.filter((r) => !fresh.has(`${r.case}/${r.job}`)), ...results];
  }
  results.sort((a, b) => `${a.case}${a.job}`.localeCompare(`${b.case}${b.job}`));
  writeFileSync(recordsPath, `${JSON.stringify(results, null, 2)}\n`, "utf8");
}

const status = { model: modelName };

/**
 * Why did steps fail? A model that invents block ids is untrustworthy; a model
 * that paraphrases accurately is merely imprecise. The verifier rejects both,
 * so the report has to separate them or the pass rate is unreadable.
 */
function classifyFailures(list) {
  const out = { paraphrase: 0, fabricated: 0, uncited: 0, total: 0 };
  for (const r of list) {
    for (const f of r.record?.verification?.failures ?? []) {
      out.total++;
      if (/quote does not appear/.test(f)) out.paraphrase++;
      else if (/no block with evidence_id/.test(f)) out.fabricated++;
      else if (/cites no evidence/.test(f)) out.uncited++;
    }
  }
  return out;
}

// ---- Report ---------------------------------------------------------------
const lines = [
  `# Assessment job validation`,
  ``,
  `Every job run against every case, with citation verification results.`,
  `Generated by \`node scripts/validate-jobs.js\`. Model: \`${status.model}\`.`,
  ``,
  `## Summary`,
  ``,
  `| Case | Job | Verdict | Steps verified | Cited without quoting |`,
  `|------|-----|---------|----------------|-----------------------|`,
];

for (const r of results) {
  if (r.error) {
    lines.push(`| ${r.case} | ${r.job} | ERROR | — | — |`);
    continue;
  }
  const v = r.record.verification;
  lines.push(
    `| ${r.case} | ${r.job} | ${r.record.verdict} | ${v ? `${v.verified_steps}/${v.total_steps}` : "—"} | ${v?.weak_steps ?? 0} |`
  );
}

const ok = results.filter((r) => !r.error && r.record.verification?.verified).length;
const runs = results.length;
const fails = classifyFailures(results);
const verdictCounts = results.reduce((acc, r) => {
  const k = r.error ? "error" : r.record.verdict;
  acc[k] = (acc[k] ?? 0) + 1;
  return acc;
}, {});

lines.push(
  ``,
  `**${ok}/${runs} runs passed mechanical citation verification.**`,
  ``,
  Object.entries(verdictCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([k, n]) => `${n} ${k}`)
    .join(" · "),
  ``,
  `Note the spread. A protocol that rubber-stamped everything would return one`,
  `verdict; this one discriminates, and it fails its own author's tool more often`,
  `than it passes it.`,
  ``,
  `## Why steps failed — the part that matters`,
  ``,
  `A pass rate on its own is unreadable, because "the model invented a citation"`,
  `and "the model paraphrased accurately" both fail verification while meaning`,
  `opposite things.`,
  ``,
  `| Failure kind | Count | What it means |`,
  `|---|---|---|`,
  `| Quote not verbatim | ${fails.paraphrase} | Model summarised the block instead of quoting it |`,
  `| Cited a nonexistent block | ${fails.fabricated} | Model invented a source |`,
  `| Cited nothing at all | ${fails.uncited} | Model asserted without pointing anywhere |`,
  ``,
  fails.fabricated === 0 && fails.total > 0
    ? `**Every single failure was paraphrase. The model never once invented a block id.**\n\n` +
      `That reframes the pass rate. The failures are not hallucination; they are a model\n` +
      `writing "the judge concluded roughly 1 in 300" where the block says "I concluded\n` +
      `that there is approximately a 1 in 300 chance". Substantively right, not verbatim.\n\n` +
      `We reject those anyway, and we think that is correct — a verifier that accepts\n` +
      `paraphrase cannot tell accurate paraphrase from convenient paraphrase, and the\n` +
      `whole value of stage 2 is that it does not have to make that judgment. But the\n` +
      `honest reading of "${ok}/${runs}" is "the conclusions were largely sound and the\n` +
      `quoting was sloppy", not "the model was unreliable".`
    : `Fabricated citations: ${fails.fabricated}. These are the serious failures — a model` +
      ` inventing a source is the exact behaviour this stage exists to catch.`,
  ``,
  `The cost of that strictness is real and we pay it here: ${fails.paraphrase} steps with`,
  `sound reasoning were marked unverified for imprecise quoting. A larger model quotes`,
  `more faithfully, which is the cheapest available fix.`,
  ``,
  `## Conclusions`,
  ``
);

for (const r of results) {
  if (r.error) {
    lines.push(`### ${r.case} / ${r.job}`, ``, `ERROR: ${r.error}`, ``);
    continue;
  }
  const rec = r.record;
  lines.push(
    `### ${r.case} / ${r.job} — ${rec.verdict}`,
    ``,
    `**${ADJUDICATION_JOBS[r.job].desideratum}**`,
    ``,
    `${rec.conclusion ?? "(no conclusion returned)"}`,
    ``
  );
  if (rec.assumption) lines.push(`_Load-bearing assumption:_ ${rec.assumption}`, ``);

  const panel = rec.challenge_panel;
  if (panel?.challenges?.length) {
    lines.push(
      `_Challenge panel — independence ${panel.independence_grade}, ` +
        `${panel.documents} challenge(s) across ${panel.lineages} lineage(s):_`,
      ``
    );
    for (const c of panel.challenges) {
      if (!c.verdict) continue;
      const who = c.model ? `${c.route} \`${c.model}\`` : c.route;
      lines.push(
        `- **${c.independent ? "independent" : "correlated"}** · ${who} · ` +
          `${c.verdict}/${c.severity ?? "?"} — ${c.strongest_objection ?? "(no objection text)"}`
      );
      for (const o of c.objections ?? []) {
        lines.push(`  - \`${o.check}\` ${o.name} [${o.severity}]: ${o.objection}`);
      }
    }
    lines.push(``);
  } else if (rec.challenge?.strongest_objection) {
    // Record written before the challenge panel existed.
    lines.push(
      `_Blind challenge (${rec.challenge.verdict}/${rec.challenge.severity}):_ ${rec.challenge.strongest_objection}`,
      ``
    );
  }
  if (rec.challenge_error) lines.push(`_Model challenge failed:_ ${rec.challenge_error}`, ``);
  if (rec.verification?.failures?.length) {
    lines.push(`_Citation failures:_`, ...rec.verification.failures.map((f) => `- ${f}`), ``);
  }
}

writeFileSync(join(outDir, "JOB_VALIDATION.md"), `${lines.join("\n")}\n`, "utf8");

console.log(`\n${ok}/${runs} passed citation verification`);
console.log(`Report:  docs/validation/JOB_VALIDATION.md`);
console.log(`Records: docs/validation/records.json`);
